spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db2
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate.hbm2ddl.auto: update
    show-sql: true
  aop:
    auto: false
custom_property: 100